### PR TITLE
Allow overriding template variables from QS

### PR DESCRIPTION
**Pull request by marekjelen**
E.g. `http://localhost:8080/?MASTERS=5#/workshop/roadshow/module/environment` overrides number of master on the environment page.

**Warning:** the query string has to be before anchor that is used for page routing, i.e. `?` has to be before `#`

### CODE REVIEW

**Comment by siamaksade** [comment]
Looks good but what's the usecase?

**Comment by thoraxe** [comment]
1) sending random people to labs.openshift3roadshow.com with customized information they can use in their own environment
2) "fixing"/tweaking/testing a running instance

**Comment by siamaksade** [comment]
If the user clicks on any link (next, prev, module, etc) doesn't he lose the query string and the values are back to default?

**Comment by thoraxe** [comment]
That needs to not happen for this to be useful :)

**Comment by marekjelen** [comment]
yes, the QS should be persistent, when only the anchor is changed

**Pull request merged**
